spring.application.name=slts-expense-tracker

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/expense_tracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:SULAaaaaa123#}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.time-zone=UTC

app.jwt.secret=${JWT_SECRET:change-this-secret-to-a-long-random-value-at-least-32-bytes}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

app.otp.expiration-minutes=${OTP_EXPIRATION_MINUTES:10}


# ==========================================
# Gmail SMTP Configuration
# ==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=tharindait@gmail.com
spring.mail.password=jyjjpiqywfzpovkp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${spring.mail.username}